image: openjdk:8

variables:
  VERSION: "1.0.0"
  DOCKER_DRIVER: overlay2

stages:
#  - test
  - build
  - dockerise
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

#test:
#  stage: test
#  before_script:
#    - export GRADLE_USER_HOME=`pwd`/.gradle
#  script:
#    - sed -i 's/<env>/test/' src/main/resources/application.properties
#    - sed -i -e "s/<es-cluster-name>/$ES_DEV_CLUSTER_NAME/" -e "s/<es-host-name>/$ES_DEV_HOST_NAME/" -e "s/<es-port>/$ES_DEV_PORT/" src/main/resources/application-test.properties
#    - ./gradlew clean test
#  allow_failure: true
#  tags:
#    - dcap-gitlab-runner

build_dev:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - sed -i 's/<env>/dev/' src/main/resources/application.properties
    - sed -i -e "s/<es-cluster-name>/$ES_DEV_CLUSTER_NAME/" -e "s/<es-host-name>/$ES_DEV_HOST_NAME/" -e "s/<es-port>/$ES_DEV_PORT/" src/main/resources/application-dev.properties
    - ./gradlew clean build -x test
  tags:
    - dcap-gitlab-runner
  artifacts:
    paths:
      - build/libs/source-annotation-helper-${VERSION}.jar
  only:
    - master
    - dcp-3300-prod-deploy

build_docker_image:
  image: docker:stable
  tls_verify: false
  privileged: true
  services:
    - docker:dind
  stage: dockerise
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    CONTAINER_RUNTIME_IMAGE: runtime
    CONTAINER_APP_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN
    - docker build --no-cache --rm=true -t $CONTAINER_APP_IMAGE .
    - docker push $CONTAINER_APP_IMAGE
  after_script:
    - docker logout ${CI_REGISTRY}
  tags:
    - dcap-gitlab-runner
  dependencies:
    - build_dev
  artifacts:
    expire_in: 1 day
    paths:
      - dist
  only:
    - master
    - dcp-3300-prod-deploy

deploy_dev:
  stage: deploy
  before_script:
    # Setup SSH deploy keys
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - chmod u+x build/libs/source-annotation-helper-${VERSION}.jar
    - scp -o StrictHostKeyChecking=no build/libs/source-annotation-helper-${VERSION}.jar ena_adm@wp-p1m2-69:/nfs/public/rw/ena/source-annotation-helper/deploy
  tags:
    - dcap-gitlab-runner
  dependencies:
    - build_dev
  environment:
    name: dev
    url: https://wwwdev.ebi.ac.uk/ena/sah/api/
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - sed -i "s|TAG|$CI_COMMIT_SHA|g" k8s-deployment.yaml
    - export KUBECONFIG=/home/gitlab-runner/.kube/<<webadmin-01-team-adm>> &&  kubectl apply -f k8s-deployment.yaml
  tags:
    - dcap-gitlab-runner
  environment:
    name: prod
    url: https://www.ebi.ac.uk/ena/sah/api/
  when: manual
  only:
    - master
