image: openjdk:17.0.2-slim-buster

variables:
  VERSION: "1.2.0-beta-5"
  DOCKER_DRIVER: overlay2
  CONTAINER_APP_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$VERSION

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  ## Set timezone, default gitlab/docker can cause problem with DB
  - TZ=Europe/London
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  ## SSH config
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - sed -i -e "s/<k8s_hh_wp_37_cluster_auth>/$K8S_HH_WP_37_CLUSTER_AUTH/" -e "s/<k8s_hh_wp_37_server>/$K8S_HH_WP_37_SERVER/" -e "s/<k8s_hh_wp_37_cluster>/$K8S_HH_WP_37_CLUSTER/" -e "s/<k8s_hh_wp_37_user>/$K8S_HH_WP_37_USER/" -e "s/<k8s_hh_wp_37_user_token>/$K8S_HH_WP_37_USER_TOKEN/" Kubernetes-cluster.yaml
  - export KUBECONFIG=./Kubernetes-cluster.yaml
stages:
  - test
  - build
  - dockerise
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - sed -i 's/<env>/test/' src/main/resources/application.properties
    - sed -i -e "s/<k8s_es_username>/$K8S_ES_USERNAME/" -e "s/<k8s_es_password>/$K8S_ES_PASSWORD/" -e "s/<es-port>/$ES_DEV_PORT/" src/main/resources/application-test.properties
    - ./gradlew clean test
  allow_failure: true
  tags:
    - dcap-gitlab-runner

build_dev:
  stage: build
  script:
    - sed -i 's/<env>/dev/' src/main/resources/application.properties
    - sed -i -e "s/<k8s_es_username>/$K8S_ES_USERNAME/" -e "s/<k8s_es_password>/$K8S_ES_PASSWORD/" -e "s/<es-port>/$ES_DEV_PORT/" src/main/resources/application-dev.properties
    - ./gradlew clean build -x test
  tags:
    - dcap-gitlab-runner
  artifacts:
    paths:
      - build/libs/source-annotation-helper-${VERSION}.jar
  only:
    - master
    - dcp-3441-ncbi-format-changes

deploy_dev:
  stage: deploy
  script:
    - chmod u+x build/libs/source-annotation-helper-${VERSION}.jar
    - scp -o StrictHostKeyChecking=no build/libs/source-annotation-helper-${VERSION}.jar ena_adm@wp-p1m2-69:/nfs/public/rw/ena/source-annotation-helper/deploy
  tags:
    - dcap-gitlab-runner
  dependencies:
    - build_dev
  environment:
    name: dev
    url: https://wwwdev.ebi.ac.uk/ena/sah/api/
  only:
    - master

build_prod:
  stage: build
  script:
    - sed -i 's/<env>/prod/' src/main/resources/application.properties
    - sed -i -e "s/<k8s_es_username>/$K8S_ES_USERNAME/" -e "s/<k8s_es_password>/$K8S_ES_PASSWORD/" -e "s/<es-port>/$ES_PROD_PORT/" src/main/resources/application-prod.properties
    - ./gradlew clean build -x test
  tags:
    - dcap-gitlab-runner
  artifacts:
    paths:
      - build/libs/source-annotation-helper-${VERSION}.jar
  only:
    - master
    - dcp-3441-ncbi-format-changes

build_docker_image:
  image: docker:stable
  services:
    - name: docker:dind
      alias: docker
      command: [ "--tls=false" ]
  stage: dockerise
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    CONTAINER_RUNTIME_IMAGE: runtime
  script:
    - sed -i -e "s/<app_version>/$VERSION/" Dockerfile
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN
    - docker build --no-cache --rm=true -t $CONTAINER_APP_IMAGE .
    - docker push $CONTAINER_APP_IMAGE
  after_script:
    - docker logout ${CI_REGISTRY}
  tags:
    - dcap-gitlab-runner-docker
  dependencies:
    - build_prod
  artifacts:
    expire_in: 1 day
    paths:
      - dist
  only:
    - master
    - dcp-3441-ncbi-format-changes

k8s-deploy-dev:
  image: dtzar/helm-kubectl
  stage: deploy
  only:
    - master
    - dcp-3441-ncbi-format-changes
  script:
    - sed -i -e "s#<container_app_image>#$CONTAINER_APP_IMAGE#" Kubernetes-dev-deployment.yaml
    - kubectl delete secret gitlab --namespace=ena-dcap
    - kubectl create secret docker-registry gitlab --docker-server=$CI_REGISTRY --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASSWORD --docker-email=$DOCKER_EMAIL --namespace=ena-dcap
    - kubectl apply -f Kubernetes-dev-deployment.yaml --namespace=ena-dcap
  tags:
    - dcap-gitlab-runner-docker
  when: manual

k8s-deploy-prod:
  image: dtzar/helm-kubectl
  stage: deploy
  only:
    - tags
    - master
    - dcp-3441-ncbi-format-changes
  script:
    - sed -i -e "s#<container_app_image>#$CONTAINER_APP_IMAGE#" Kubernetes-prod-deployment.yaml
    - kubectl delete secret gitlab --namespace=ena-dcap
    - kubectl create secret docker-registry gitlab --docker-server=$CI_REGISTRY --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASSWORD --docker-email=$DOCKER_EMAIL --namespace=ena-dcap
    - kubectl apply -f Kubernetes-prod-deployment.yaml --namespace=ena-dcap
  tags:
    - dcap-gitlab-runner-docker
  when: manual
