image: java:8

variables:
  VERSION: "1.0.0"

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - sed -i 's/<env>/test/' src/main/resources/application.properties
    - ./gradlew clean test
  allow_failure: true
  tags:
    - dcap-gitlab-runner

build_dev:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - sed -i 's/<env>/dev/' src/main/resources/application.properties
    - ./gradlew clean build -x test
  tags:
    - dcap-gitlab-runner
  artifacts:
    paths:
      - build/libs/source-annotation-helper-${VERSION}.jar
  only:
    - master
    - dcp-3148-initial

deploy_dev:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\tHostKeyAlgorithms +ssh-rsa\n\tPubkeyAcceptedAlgorithms +ssh-rsa\n" > ~/.ssh/config
  script:
    - chmod u+x build/libs/source-annotation-helper-${VERSION}.jar
    - scp -o StrictHostKeyChecking=no build/libs/source-annotation-helper-${VERSION}.jar ena_adm@wp-p1m2-69:/nfs/public/rw/ena/source-annotation-helper/deploy
  tags:
    - dcap-gitlab-runner
  dependencies:
    - build_dev
  environment:
    name: dev
    url: https://wwwdev.ebi.ac.uk/ena/sah/api/
  only:
    - master
    - dcp-3148-initial

build_prod:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - sed -i 's/<env>/prod/' src/main/resources/application.properties
    - ./gradlew clean build -x test
  tags:
    - dcap-gitlab-runner
  artifacts:
    paths:
      - build/libs/source-annotation-helper-${VERSION}.jar
  only:
    - master

deploy_prod:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\tHostKeyAlgorithms +ssh-rsa\n\tPubkeyAcceptedAlgorithms +ssh-rsa\n" > ~/.ssh/config
  script:
    - chmod u+x build/libs/source-annotation-helper-${VERSION}.jar
    - scp -o StrictHostKeyChecking=no build/libs/source-annotation-helper-${VERSION}.jar ena_adm@SERVER_NAME:/nfs/public/rw/ena/source-annotation-helper/deploy
  tags:
    - dcap-gitlab-runner
  dependencies:
    - build_prod
  environment:
    name: prod
    url: https://www.ebi.ac.uk/ena/sah/api/
  when: manual
  only:
    - master
