image: openjdk:17.0.2-slim-buster

variables:
  VERSION: "1.2.0-beta"
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build
  - dockerise
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - sed -i 's/<env>/test/' src/main/resources/application.properties
    - sed -i -e "s/<k8s_es_username>/$K8S_ES_USERNAME/" -e "s/<k8s_es_password>/$K8S_ES_PASSWORD/" -e "s/<es-port>/$ES_DEV_PORT/" src/main/resources/application-test.properties
    - ./gradlew clean test
  allow_failure: true
  tags:
    - dcap-gitlab-runner

build_dev:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - sed -i 's/<env>/dev/' src/main/resources/application.properties
    - sed -i -e "s/<k8s_es_username>/$K8S_ES_USERNAME/" -e "s/<k8s_es_password>/$K8S_ES_PASSWORD/" -e "s/<es-port>/$ES_DEV_PORT/" src/main/resources/application-dev.properties
    - ./gradlew clean build -x test
  tags:
    - dcap-gitlab-runner
  artifacts:
    paths:
      - build/libs/source-annotation-helper-${VERSION}.jar
  only:
    - master
    - dcp-3441-ncbi-format-changes

deploy_dev:
  stage: deploy
  before_script:
    # Setup SSH deploy keys
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - chmod u+x build/libs/source-annotation-helper-${VERSION}.jar
    - scp -o StrictHostKeyChecking=no build/libs/source-annotation-helper-${VERSION}.jar ena_adm@wp-p1m2-69:/nfs/public/rw/ena/source-annotation-helper/deploy
  tags:
    - dcap-gitlab-runner
  dependencies:
    - build_dev
  environment:
    name: dev
    url: https://wwwdev.ebi.ac.uk/ena/sah/api/
  only:
    - master

build_prod:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - sed -i 's/<env>/prod/' src/main/resources/application.properties
    - sed -i -e "s/<k8s_es_username>/$K8S_ES_USERNAME/" -e "s/<k8s_es_password>/$K8S_ES_PASSWORD/" -e "s/<es-port>/$ES_PROD_PORT/" src/main/resources/application-prod.properties
    - ./gradlew clean build -x test
  tags:
    - dcap-gitlab-runner
  artifacts:
    paths:
      - build/libs/source-annotation-helper-${VERSION}.jar
  only:
    - master

build_docker_image:
  image: docker:stable
  services:
    - docker:dind
  stage: dockerise
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    CONTAINER_RUNTIME_IMAGE: runtime
    CONTAINER_APP_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$VERSION
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN
    - docker build --no-cache --rm=true -t $CONTAINER_APP_IMAGE .
    - docker push $CONTAINER_APP_IMAGE
  after_script:
    - docker logout ${CI_REGISTRY}
  tags:
    - dcap-gitlab-runner-docker
  dependencies:
    - build_prod
  artifacts:
    expire_in: 1 day
    paths:
      - dist
  only:
    - master
    - dcp-3441-ncbi-format-changes

deploy_prod:
  stage: deploy
  script:
    - sed -i "s|TAG|$VERSION|g" k8s-deployment.yaml
    - export KUBECONFIG=/home/gitlab-runner/.kube/<<webadmin-01-team-adm>> &&  kubectl apply -f k8s-deployment.yaml
  tags:
    - dcap-gitlab-runner
  environment:
    name: prod
    url: https://www.ebi.ac.uk/ena/sah/api/
  when: manual
  only:
    - master
