apiVersion: apps/v1
kind: Deployment
metadata:
  name: ena-dcap-sah-prod
  namespace: ena-dcap
spec:
  selector:
    matchLabels:
      app: ena-dcap-sah-prod
  replicas: 2
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: ena-dcap-sah-prod
    spec:
      containers:
        - name: ena-dcap-sah-prod
          image: <container_app_image>
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ena/sah/api/actuator/health?client=k8s
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 120
            failureThreshold: 1
          env:
            - name: JAVA_OPTS
              value: "-Dhttp.proxyHost=pg-wwwcache.ebi.ac.uk -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts=localhost|.cluster.local -Dhttps.proxyHost=pg-wwwcache.ebi.ac.uk -Dhttps.proxyPort=3128"
            - name: ES-HH-PROD-HOST
              valueFrom:
                configMapKeyRef:
                  name: es-hh-prod-host
                  key: host
            - name: ES-HH-PROD-PORT
              valueFrom:
                configMapKeyRef:
                  name: es-hh-prod-host
                  key: port
            - name: K8S_ES_RO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: es-hh-prod-ro-credentials
                  key: username
            - name: K8S_ES_RO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-hh-prod-ro-credentials
                  key: password
            - name: ES-HH-PROD-CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: es-hh-prod-certificate
                  key: hh-cert.cer
      imagePullSecrets:
        - name: regcred

---
kind: Service
apiVersion: v1
metadata:
  name: ena-dcap-sah-prod
  namespace: ena-dcap
spec:
  selector:
    app: ena-dcap-sah-prod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31025
  type: NodePort
