apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: <k8s_hx_wp_38_cluster_auth>
      server: https://<k8s_hx_wp_38_server>
    name: <k8s_hx_wp_38_cluster>
contexts:
  - context:
      cluster: <k8s_hx_wp_38_cluster>
      user: <k8s_hx_wp_38_user>
    name: <k8s_hx_wp_38_user>
current-context: <k8s_hx_wp_38_user>
kind: Config
preferences: {}
users:
  - name: <k8s_hx_wp_38_user>
    user:
      token: <k8s_hx_wp_38_user_token>
