apiVersion: apps/v1
kind: Deployment
metadata:
  name: ena-dcap-sah-prod
  namespace: ena-dcap
spec:
  selector:
    matchLabels:
      app: ena-dcap-sah-prod
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: ena-dcap-sah-prod
    spec:
      containers:
        - name: ena-dcap-sah-prod
          image: <container_app_image>
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Dhttp.proxyHost=pg-wwwcache.ebi.ac.uk -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts=localhost|.cluster.local -Dhttps.proxyHost=pg-wwwcache.ebi.ac.uk -Dhttps.proxyPort=3128"
            - name: ES-PROD-HOST
              valueFrom:
                configMapKeyRef:
                  name: es-prod-host
                  key: host
            - name: ES-PROD-PORT
              valueFrom:
                configMapKeyRef:
                  name: es-prod-host
                  key: port
            - name: ES-PROD-USERNAME
              valueFrom:
                secretKeyRef:
                  name: es-prod-credentials
                  key: username
            - name: ES-PROD-PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-prod-credentials
                  key: password
            - name: ES-PROD-CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: es-prod-certificate
                  key: hh-cert.cer
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        appType: ena-dcap-web

---
kind: Service
apiVersion: v1
metadata:
  name: ena-dcap-sah-prod
  namespace: ena-dcap
spec:
  selector:
    app: ena-dcap-sah-prod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31025
  type: NodePort
